---
 - hosts: localhost
   connection: local
   tasks:
   - name: Installing All neccessary packages
     become: yes
     become_user: root
     apt:
       pkg:
         - apache2
         - mysql-server
         - php
         - php-mysql
         - php-xml
         - php-mbstring
         - php-intl
         - python3-pip
         - libapache2-mod-php
       state: present
       update_cache: yes
